# Lista compilada dos screenshots do repositório HuggingFace.
# Domínios corrompidos pelo Google Tradutor foram corrigidos manualmente
# (ex: "ao vivo.com" -> "live.com"). Casos ambíguos foram removidos.

PROVIDERS = [
    "21cn.com","abc.com","adelphia.net","aim.com","alice.it","aliceadsl.fr",
    "alltel.net","ameritech.net","amorki.pl","anzeigenschleuder.com","aol.co.uk",
    "aol.com","aol.de","aol.net","aon.at","arcor.de","atlanticbb.net","atlas.cz",
    "att.net","attbi.com","austin.rr.com","avantel.com.mx","azet.sk","bbox.fr",
    "bebo.com","bellsouth.com","bellsouth.net","bigmir.net","bigpond.com.au",
    "bigpond.com","bigpond.net.au","bk.ru","blackplanet.com","bluewin.ch",
    "blueyonder.co.uk","bol.com.br","breakthru.com","bresnan.net","btconnect.com",
    "btinternet.com","btopenworld.com","buziaczek.pl","cableone.net","caramail.com",
    "carolina.rr.com","cegetel.net","cemsmail.org","centrum.cz","centrum.sk",
    "centurytel.net","cfl.rr.com","charter.net","cinci.rr.com","citromail.hu",
    "clear.net.nz","clearwire.net","club-internet.fr","cogeco.ca","columbus.rr.com",
    "comcast.com","comcast.net","cox.com","cox.net","cs.com","daum.net","dell.com",
    "docomo.ne.jp","dodgeit.com","dodo.com.au","dreamwiz.com","e-mail.com",
    "earthlink.com","earthlink.net","eircom.net","email.com","email.cz","email.it",
    "email.su","embarqmail.com","empal.com","epix.net","epost.de","excite.com",
    "eyou.com","ezweb.ne.jp","fastwebnet.it","flash.net","foxmail.com",
    "freechal.com","freelymail.com","freemail.hu","freemailmail.com","freenet.de",
    "fromru.com","frontier.com","frontiernet.net","fsmail.net","fuse.net",
    "gadball.com","gaggle.net","gamil.com","gawab.com","gazeta.pl","gci.net",
    "globo.com","gmai.com","gmail.com.tw","gmail.com","gmail.net","gmail.ru",
    "gmal.com","gmial.com","gmx.at","gmx.ch","gmx.co.uk","gmx.com","gmx.de",
    "gmx.net","gmx.ru","gmx.us","go.com","google.com","googlemail.com",
    "hanmail.net","hanmir.com","hellokitty.com","hjhrb.com","homemail.com",
    "home.com","home.nl","hot.com","hotel.com","hotmai.com","hotmail.be",
    "hotmail.ca","hotmail.co.jp","hotmail.co.th","hotmail.co.uk","hotmail.co",
    "hotmail.com.ar","hotmail.com.au","hotmail.com.br","hotmail.com","hotmail.de",
    "hotmail.dk","hotmail.es","hotmail.fr","hotmail.it","hotmail.net","hotmail.nl",
    "hotmail.se","hotmaill.com","hotmal.com","hotmial.com","hotmil.com",
    "houston.rr.com","hoymail.com","htmail.com","htomail.com","hughes.net",
    "hushmail.com","i.softbank.jp","i.ua","icloud.com","ig.com.br","iinet.net.au",
    "inbox.com","inbox.lv","inbox.ru","inboxsky.com","indiatimes.com",
    "infosel.net.mx","insightbb.com","interia.eu","interia.pl","inwind.it",
    "iprimus.com.au","istruzione.it","iwon.com","juno.com","katamail.com",
    "kc.rr.com","kimo.com","knology.net","laposte.net","latinmail.com","lenta.ru",
    "libero.it","lineone.net","lista.ru","viva.be","live.ca","live.co.uk",
    "live.com.ar","live.com.au","live.com.mx","live.com.pt","live.com","live.de",
    "live.dk","live.fr","live.it","live.nl","live.no","live.se","localnet.com",
    "luukku.com","lycos.co.kr","lycos.com","lycos.de","mac.com","mail.bg",
    "mail.com","mail.ru","mail.ua","mailcatch.com","mailcity.com","mchsi.com",
    "me.com","meta.ua","microsoft.com","migente.com","mindspring.com",
    "mocospace.com","msa.hinet.net","msn.com","myemailboxmail.com","mynet.com",
    "myspace.com","myway.com","nate.com","naver.com","nc.rr.com","neo.rr.com",
    "net.hr","netscape.com","netscape.net","netsync.net","netzero.com",
    "netzero.net","neuf.fr","nifty.com","nomail.com","noos.fr","ntlworld.com",
    "numericable.fr","nyc.rr.com","nycap.rr.com","o2.pl","oi.com.br","okdc.com",
    "ol.com","onet.eu","onet.pl","online.de","online.ee","online.fr","online.no",
    "ono.com","op.pl","operamail.com","optonline.net","optusnet.com.au",
    "orange.fr","orange.net","orange.pl","otmail.com","outlook.com","outlook.fr",
    "ovi.com","pacbell.net","pandora.be","paran.com","pchome.com.tw",
    "peoplepc.com","pisem.net","planet.nl","pochta.ru","poczta.fm",
    "poczta.onet.pl","poczta.pl","post.com","post.sk","pp.com","prodigy.net.mx",
    "prodigy.net","ptd.net","q.com","qip.ru","qq.com","rambler.ru","rcn.com",
    "rediff.com","rediffmail.com","roadrunner.com","rochester.rr.com","rock.com",
    "rocketmail.com","rogers.com","rr.com","sapo.pt","satx.rr.com","sayclub.com",
    "sbc.com","sbcglobal.com","sbcglobal.net","sc.rr.com","sexy.com","seznam.cz",
    "sfr.fr","shaw.ca","sibmail.com","sify.com","sina.com","singnet.com.sg",
    "sky.com","skynet.be","snet.net","social.rr.com","sohu.com","sprintpcs.com",
    "stny.rr.com","student.gccisd.net","suddenlink.net","swbell.net",
    "sympatico.ca","t-online.de","talk21.com","talktalk.net","tampabay.rr.com",
    "tds.net","telefonica.net","telenet.be","telia.com","telkomsa.net",
    "telus.net","terra.com.br","terra.es","tesco.net","tianya.cn","tin.it",
    "tiscali.co.uk","tiscali.it","tjbio.com","tlen.pl","tmail.com",
    "tmo.blackberry.net","tom.com","tpg.com.au","trbvm.com","triad.rr.com",
    "twcny.rr.com","tx.rr.com","ua.fm","ukr.net","univision.com","uol.com.br",
    "usa.com","usa.net","verizon.com","verizon.net","veryzon.net","videotron.ca",
    "vip.qq.com","vipmail.net","virgilio.it","virgin.net","virginmedia.com",
    "voila.fr","volny.cz","vp.pl","vzw.blackberry.net","walla.co.il","walla.com",
    "wanadoo.fr","wanadoo.nl","web.de","webtv.net","westnet.com.au",
    "westpost.net","who.net","wi.rr.com","wildblue.net","windowslive.com",
    "windstream.net","wmconnect.com","woh.rr.com","worldnet.att.net",
    "wowway.com","wp.eu","wp.pl","xtra.co.nz","y7mail.com","ya.ru","yahoo.ca",
    "yahoo.cn","yahoo.co.id","yahoo.co.in","yahoo.co.jp","yahoo.co.kr",
    "yahoo.co.nz","yahoo.co.uk","yahoo.co","yahoo.com.ar","yahoo.com.au",
    "yahoo.com.br","yahoo.com.cn","yahoo.com.hk","yahoo.com.mx","yahoo.com.my",
    "yahoo.com.ph","yahoo.com.sg","yahoo.com.tw","yahoo.com.ua","yahoo.com.vn",
    "yahoo.com","yahoo.de","yahoo.dk","yahoo.es","yahoo.fr","yahoo.gr",
    "yahoo.ie","yahoo.in","yahoo.it","yahoo.net","yahoo.no","yahoo.pl",
    "yahoo.se","yahoomail.com","yandex.com.ru","yandex.com.ua","yandex.com",
    "yandex.net.ru","yandex.net","yandex.ru","yandex.ua","sim.net","ymail.com",
    "yorku.ca","ziggo.nl","zoominternet.net",
]

# Provedores prioritários (os 🟡 do levantamento anterior) — sinalizados
# no relatório final para facilitar o follow-up com caixa real.
PRIORITY = {
    "seznam.cz","interia.pl","interia.eu","onet.pl","onet.eu","poczta.onet.pl",
    "libero.it","virgilio.it","tiscali.it","tiscali.co.uk","centrum.cz",
    "centrum.sk","rambler.ru","naver.com","qq.com","vip.qq.com","sapo.pt",
}
